# Generated by Django 4.2 on 2023-04-16 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='banners/')),
                ('buttonText', models.CharField(max_length=100)),
                ('product', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=100)),
                ('smallText', models.CharField(max_length=100)),
                ('midText', models.CharField(max_length=100)),
                ('largeText', models.CharField(max_length=100)),
                ('largeText2', models.CharField(max_length=100)),
                ('discount', models.CharField(max_length=100)),
                ('saleTime', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images/')),
                ('price', models.FloatField()),
                ('details', models.CharField(max_length=200)),
                ('slug', models.SlugField()),
            ],
        ),
    ]
